import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Button} from './ui/Button';
import {ArticleTemplatePicker} from './ArticleTemplatePicker';
import {apiClient,parseApiError} from '../services/api';
import type {ArticleRecord,ArticlePreview,ResearchDraft} from '../../../src/lib/article-types';
const stageLabels:Record<string,string>={config:'准备配置',read:'读取原始资料',search:'搜索并读取公开资料',diagnose:'确定写作方向',evidence:'整理资料与事实',outline:'组织提纲',draft:'写作正文',review:'编辑审校',illustrations:'规划配图',assets:'制作封面与示意图',preview:'检查文章预览'};
const inputClass='mt-2 w-full rounded-lg border border-line-ui bg-canvas p-3 text-sm leading-7 text-ink';
export function ArticleAutoWorkspace({article:a,onUpdated,onAdvanced,onProtected}:{article:ArticleRecord;onUpdated:(a:ArticleRecord)=>void;onAdvanced:()=>void;onProtected:(value:boolean)=>void}){
 const key=`douyin-ai-video.article-auto-edit.${a.id}`;
 const [edit,setEdit]=useState<Record<string,unknown>>({}),[baseVersion,setBaseVersion]=useState(a.version);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState<'preview'|'edit'|'layout'>('preview');
 const [html,setHtml]=useState(''),[previewError,setPreviewError]=useState(''),[previewBusy,setPreviewBusy]=useState(false),[urls,setUrls]=useState<Record<string,string>>({});
 const [supplement,setSupplement]=useState(''),[checked,setChecked]=useState(false),[deliveryPreview,setDeliveryPreview]=useState<ArticlePreview>();
 const [inputMode,setInputMode]=useState<'idea'|'text'>('idea'),[publicQuery,setPublicQuery]=useState(''),[publicConfirmed,setPublicConfirmed]=useState(false);
 const dirty=Object.keys(edit).length>0,active=!!a.automation&&['queued','running','cancelling'].includes(a.automation.status),locked=busy||active;
 const view={...a,...edit} as ArticleRecord,draft=view[view.adopted]??view.draft;
 const version=dirty?baseVersion:a.version;
 const legacyInputError=a.automation?.error?.code==='ai_output_invalid'&&a.input?.kind==='text'&&!a.sources.some(s=>s.included&&s.status==='readable'&&(s.kind!=='text'||s.text!==a.input?.raw));
 const canCorrectInput=!active&&!draft&&!!a.input&&['text','idea'].includes(a.input.kind)&&(legacyInputError||['needs_public_query','needs_material','ai_facts_empty'].includes(a.automation?.error?.code??''));
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(key)??'null');if(saved){setEdit(saved.edit);setBaseVersion(saved.version);setNotice('已恢复未保存的文章编辑');if(saved.version!==a.version)setError('本地编辑基于旧版本，已保留；请到高级编辑载入最新版本并核对后保存');}}catch{setError('本地编辑无法恢复，已保存稿件仍在本机');}},[key]);
 useEffect(()=>{try{if(dirty)localStorage.setItem(key,JSON.stringify({edit,version:baseVersion}));else localStorage.removeItem(key);}catch{setNotice('本地编辑缓存无法保存，请保存编辑到工作台');}},[dirty,edit,baseVersion,key]);
 useEffect(()=>{onProtected(dirty||busy);},[dirty,busy,onProtected]);
 useEffect(()=>()=>onProtected(false),[onProtected]);
 const ids=JSON.stringify([view.coverAssetId,...view.bodyImageAssetIds].filter(Boolean));
 useEffect(()=>{let live=true;void Promise.all((JSON.parse(ids) as string[]).map(async id=>[id,await apiClient.getAssetRawUrl(id)] as const)).then(p=>{if(live)setUrls(Object.fromEntries(p));}).catch(()=>{if(live)setPreviewError('配图暂不可用，请重载文章');});return()=>{live=false;};},[ids]);
 const request=JSON.stringify({version,layoutTemplate:view.layoutTemplate,layoutVersion:view.layoutVersion,layoutOptions:view.layoutOptions,draft,bodyImageAssetIds:view.bodyImageAssetIds,bodyImagePlacements:view.bodyImagePlacements});
 useEffect(()=>{let live=true;setHtml('');setPreviewError('');if(!draft||active){setPreviewBusy(false);return;}setPreviewBusy(true);const timer=window.setTimeout(()=>{void apiClient.previewArticleLayout(a.id,JSON.parse(request)).then(p=>{if(live)setHtml(p.html);}).catch(e=>{if(live)setPreviewError(parseApiError(e).message);}).finally(()=>{if(live)setPreviewBusy(false);});},220);return()=>{live=false;window.clearTimeout(timer);};},[a.id,request,active]);
 const resolvedHtml=html.replace(/\{\{wechat-image-(\d+)\}\}/g,(_,n)=>urls[view.bodyImageAssetIds[Number(n)-1]]??'');
 const change=(p:Record<string,unknown>)=>{if(!dirty)setBaseVersion(a.version);setEdit(current=>({...current,...p}));setChecked(false);setDeliveryPreview(undefined);};
 const act=async(fn:()=>Promise<ArticleRecord>)=>{if(busy)return;setBusy(true);setError('');try{onUpdated(await fn());}catch(e){setError(parseApiError(e).message);}finally{setBusy(false);}};
 const save=()=>act(async()=>{const result=await apiClient.saveArticle(a.id,{version,...edit});setEdit({});setBaseVersion(result.version);setNotice('文章编辑已保存');return result;});
 const resume=()=>act(async()=>{let current=a;if(supplement.trim()){current=await apiClient.saveArticle(a.id,{version:a.version,addText:{title:'用户补充的正文资料',text:supplement},sourceEdits:a.sources.filter(s=>s.included&&s.status!=='readable').map(s=>({id:s.id,included:false}))});setSupplement('');onUpdated(current);}return apiClient.resumeArticleAuto(a.id,current.version);});
 const prepareDelivery=()=>act(async()=>{const current=await apiClient.saveArticle(a.id,{version:a.version,materialConfirmed:true,outlineConfirmed:true,reviewed:true});onUpdated(current);setDeliveryPreview(await apiClient.previewArticle(a.id,current.version));return current;});
 const submit=()=>act(async()=>{const result=await apiClient.saveArticleWechatDraft(a.id,a.version,deliveryPreview!.previewRevision);setDeliveryPreview(undefined);setNotice(result.article.wechatDelivery?.message??'请查看发布记录');return result.article;});
 return <div className="mx-auto max-w-7xl space-y-6 py-4 sm:p-7">
  <header className="flex flex-wrap items-start justify-between gap-4"><div><Link to="/articles" className="text-xs text-accent">← 文章创作</Link><h1 className="mt-3 font-display text-2xl font-semibold text-ink">{draft?.title??a.keyword}</h1><p className="mt-2 text-sm text-ink-muted">{active?'正在自动创作，完成后会停在文章预览':draft?'文章与资料保存在本机，可编辑后再保存公众号草稿':'灵感已保存，等待完成文章'}。</p></div><div className="flex flex-wrap gap-2">{active?<Button variant="outline" disabled={busy||a.automation?.status==='cancelling'} onClick={()=>void act(()=>apiClient.cancelArticleAuto(a.id,a.automation!.runId))}>{a.automation?.status==='cancelling'?'正在停止…':'停止创作'}</Button>:a.automation?.status!=='ready'&&<Button variant="ai" disabled={busy||dirty} onClick={()=>void resume()}>继续自动创作</Button>}<Button variant="outline" disabled={locked} onClick={()=>void act(async()=>{const latest=await apiClient.getArticle(a.id);setBaseVersion(latest.version);setNotice('已载入最新版本，本地编辑仍保留，请核对后保存');return latest;})}>载入最新版本</Button><Button variant="outline" disabled={locked||dirty} onClick={onAdvanced}>高级编辑</Button></div></header>
  {(error||a.automation?.error?.message)&&<div role="alert" className="space-y-3 rounded-lg border border-danger-line bg-danger-soft p-4 text-sm text-danger"><p>{error||a.automation?.error?.message}</p>{a.automation?.error?.code&&<p className="text-xs">诊断代码：{a.automation.error.code}</p>}{a.automation?.error?.code==='ai_missing'&&<Link to="/settings" className="underline">去设置当前 AI →</Link>}</div>}{notice&&<p role="status" className="text-sm text-accent">{notice}</p>}
  {canCorrectInput&&<section className="space-y-3 rounded-xl border border-line bg-panel p-5"><h2 className="font-semibold text-ink">确认输入类型并继续</h2><p className="text-xs leading-6 text-ink-muted">若原输入只是问题或写作提纲，请选择公开选题；完整粘贴的正文默认直接使用，不检索。</p><label className="block text-sm text-ink">输入类型<select aria-label="恢复输入类型" value={inputMode} disabled={locked||dirty} onChange={e=>{setInputMode(e.target.value as 'idea'|'text');setPublicConfirmed(false);}} className={inputClass}><option value="idea">公开选题，需要搜索资料</option><option value="text">完整正文，直接使用</option></select></label>{inputMode==='idea'&&<><label className="block text-sm text-ink">公开搜索关键词<input aria-label="恢复公开搜索关键词" maxLength={400} value={publicQuery} disabled={locked||dirty} onChange={e=>{setPublicQuery(e.target.value);setPublicConfirmed(false);}} className={inputClass}/></label><label className="flex items-start gap-2 text-xs leading-6 text-ink-muted"><input type="checkbox" aria-label="确认公开搜索词" checked={publicConfirmed} disabled={locked||dirty} onChange={e=>setPublicConfirmed(e.target.checked)}/>我确认这些关键词可发送给已有搜索服务，不包含私人信息。原输入保留参考，不作为事实来源。</label></>}<Button disabled={locked||dirty||inputMode==='idea'&&(!publicConfirmed||!publicQuery.trim())} onClick={()=>void act(()=>apiClient.resumeArticleAuto(a.id,a.version,{inputMode,...(inputMode==='idea'?{searchQuery:publicQuery.trim()}:{})}))}>按所选类型继续创作</Button></section>}
  <details open={active||!draft} className="rounded-xl border border-line bg-panel p-4"><summary className="cursor-pointer text-sm text-ink">创作进度 · {active?stageLabels[a.automation!.stage]:a.automation?.status==='ready'?'已完成，待你核对':a.automation?.status==='cancelled'?'已停止，成果保留':'可查看或继续'}</summary><ol className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(stageLabels).map(([id,label])=>{const state=a.automation?.checkpoints[id as keyof typeof a.automation.checkpoints]?.status;return <li key={id} className="text-xs leading-6 text-ink-muted"><span className={state==='failed'?'text-danger':state==='succeeded'?'text-success':state==='running'?'text-accent':''}>{state==='succeeded'?'✓':state==='failed'?'!':state==='running'?'…':'○'} {label}</span></li>;})}</ol><p className="mt-3 text-xs leading-6 text-ink-subtle">AI 审校不等于事实认证，保存草稿前仍需核对来源与局限。</p></details>
  {a.automation?.status==='needs_input'&&a.automation.error?.code!=='ai_missing'&&<section className="space-y-3 rounded-xl border border-line bg-panel p-5"><label className="block text-sm text-ink">补充可用正文<textarea aria-label="补充正文" rows={5} maxLength={30000} value={supplement} onChange={e=>setSupplement(e.target.value)} className={inputClass}/></label><p className="text-xs leading-6 text-ink-muted">补充后将使用这份正文；读取失败的链接保留参考并排除。也可在高级编辑更换链接。</p><Button disabled={busy||dirty||!supplement.trim()} onClick={()=>void resume()}>以补充正文继续</Button></section>}
  {a.automation?.research&&<details className="rounded-xl border border-line bg-panel p-4"><summary className="cursor-pointer text-sm text-ink">公开资料检索 · {a.automation.research.candidates.filter(c=>c.status==='readable').length}份正文</summary><p className="mt-3 break-all text-xs leading-6 text-ink-muted">搜索词：{a.automation.research.query} · 检索时间：{a.automation.research.fetchedAt??'未完成'}</p>{a.automation.research.message&&<p role="status" className="mt-2 text-xs leading-6 text-warning">{a.automation.research.message}</p>}<p className="mt-2 text-xs leading-6 text-ink-subtle">优先尝试官方与文档来源，仅全文读取成功的资料参与写作；搜索排序不代表来源已核实，转载也不算独立佐证。</p><ul className="mt-3 space-y-3">{a.automation.research.candidates.map(c=>{const s=a.sources.find(s=>s.id===c.sourceId);return <li key={c.url} className="break-words text-xs leading-6 text-ink-muted"><a href={c.url} target="_blank" rel="noreferrer" className="break-all text-accent">{c.title}</a><p>{c.status==='readable'?'已读正文':c.status==='skipped'?'重复，未采用':c.status==='failed'?'未读到正文':'未读取'} · {c.domain} · 正文发布日期：{s?.publishedAt??'未知'}{c.publishedAt&&` · 搜索报告日期：${c.publishedAt}`} · 正文读取：{s?.readAt??'未完成'}</p>{c.message&&<p>{c.message}</p>}</li>;})}</ul></details>}
  {draft&&<section className="rounded-xl border border-line bg-panel p-4 sm:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{(['preview','edit','layout'] as const).map(t=><Button key={t} variant={tab===t?'primary':'ghost'} disabled={active} onClick={()=>setTab(t)}>{t==='preview'?'文章预览':t==='edit'?'编辑正文':'模板与排版'}</Button>)}</div><Button disabled={locked||!dirty} onClick={()=>void save()}>保存文章编辑</Button></div>
   {tab==='layout'?<ArticleTemplatePicker value={view.layoutTemplate??'default'} layoutVersion={view.layoutVersion} options={view.layoutOptions} onChange={(layoutTemplate,layoutVersion,layoutOptions)=>change({layoutTemplate,layoutVersion,layoutOptions})} previewHtml={resolvedHtml} previewTitle={draft.title} previewBusy={previewBusy} previewError={previewError}/>:tab==='edit'?<fieldset disabled={locked} className="space-y-5"><label className="block text-sm text-ink">文章标题<input aria-label="文章标题" maxLength={32} value={draft.title} onChange={e=>change({[view.adopted]:{...draft,title:e.target.value}})} className={inputClass}/></label>{draft.sections.map((s,i)=><section key={i} className="space-y-3 border-t border-line pt-4"><label className="block text-xs text-ink-muted">第{i+1}节标题<input aria-label={`第${i+1}节标题`} maxLength={200} value={s.heading??''} onChange={e=>change({[view.adopted]:{...draft,sections:draft.sections.map((n,j)=>j===i?{...n,heading:e.target.value}:n)}})} className={inputClass}/></label><label className="block text-xs text-ink-muted">第{i+1}节正文（空行分段）<textarea aria-label={`第${i+1}节正文`} rows={8} value={s.paragraphs.join('\n\n')} onChange={e=>change({[view.adopted]:{...draft,sections:draft.sections.map((n,j)=>j===i?{...n,paragraphs:e.target.value.split(/\n\s*\n/).filter(Boolean)}:n)}})} className={inputClass}/></label></section>)}</fieldset>:<div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_260px]"><div className="min-w-0 rounded-lg bg-canvas p-3">{previewBusy?<p role="status" className="p-6 text-sm text-ink-muted">正在更新文章预览…</p>:previewError?<p role="alert" className="p-4 text-sm text-danger">{previewError}</p>:resolvedHtml?<iframe title="自动创作文章预览" sandbox="" srcDoc={`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><body style="margin:0">${resolvedHtml}</body>`} className="mx-auto h-[720px] w-full max-w-[390px] rounded-lg border border-line bg-white"/>:<p className="p-6 text-sm text-ink-muted">已保存稿件，等待当前阶段结束后预览。</p>}</div><aside className="space-y-5 text-sm text-ink-muted">{urls[view.coverAssetId]&&<figure><img src={urls[view.coverAssetId]} alt="当前文章封面" className="w-full rounded-lg"/><figcaption className="mt-2 text-xs">当前封面 · 本地排版图片</figcaption></figure>}<p className="text-xs leading-6">{a.automation?.templateReason}</p>{a.issues.length>0&&<div><h3 className="font-medium text-ink">资料局限</h3><p className="mt-2 text-xs leading-6">{a.issues.join('；')}</p></div>}<details><summary className="cursor-pointer">资料与审校说明</summary><div className="mt-3 space-y-3">{a.sources.map(s=><div key={s.id} className="text-xs leading-6"><p>{s.title} · {s.included?'采用':'参考，未采用'}</p><p>发布日期：{s.publishedAt??'未知'} · 正文读取：{s.readAt||'未完成'}</p>{s.url&&<a href={s.url} target="_blank" rel="noreferrer" className="break-all text-accent">{s.url}</a>}</div>)}<p className="text-xs leading-6">{a.reviewNotes.join('；')}</p></div></details></aside></div>}
  </section>}
  {draft&&<section className="space-y-4 rounded-xl border border-line bg-panel p-5"><h2 className="font-semibold text-ink">保存到公众号草稿箱</h2><p className="text-xs leading-6 text-ink-muted">目标为设置中当前配置的公众号。先检查正文、封面和图片；账号配置或保存失败时成果仍保留。此处不会正式发布或群发。</p><label className="flex items-start gap-2 text-sm text-ink"><input type="checkbox" checked={checked} disabled={locked||dirty} onChange={e=>setChecked(e.target.checked)}/>我已核对当前文章、资料局限及图片使用权</label><Button disabled={locked||dirty||!checked||a.steps.review!=='succeeded'||!a.coverAssetId||!a.bodyImageAssetIds.length||!!a.wechatDelivery&&['succeeded','uncertain','preparing'].includes(a.wechatDelivery.state)} onClick={()=>void prepareDelivery()}>保存到公众号草稿箱</Button>{dirty&&<p className="text-xs text-warning">请先保存文章编辑，再核对当前预览。</p>}{a.wechatDelivery&&<p role="status" className="text-sm text-accent">{a.wechatDelivery.message??'本地交付包已有记录，请到发布中心核对'} <Link to="/publishing?channel=wechat-mp&contentType=article" className="underline">查看发布记录 →</Link></p>}</section>}
  {deliveryPreview&&<div role="dialog" aria-modal="true" aria-label="确认保存公众号草稿" className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><section className="w-full max-w-lg space-y-5 rounded-xl border border-line bg-panel p-6"><h2 className="text-lg font-semibold text-ink">确认保存公众号草稿</h2><p className="text-sm text-ink">{deliveryPreview.title}</p>{urls[a.coverAssetId]&&<img src={urls[a.coverAssetId]} alt="将保存的文章封面" className="max-h-48 w-full rounded object-contain"/>}<p className="text-sm leading-7 text-ink-muted">保存到设置中已配置的公众号草稿箱，不会发布或群发。若目标账号不确定，请先取消并核对公众号设置。</p><div className="flex justify-end gap-3"><Button variant="outline" disabled={busy} onClick={()=>setDeliveryPreview(undefined)}>取消</Button><Button disabled={busy} onClick={()=>void submit()}>{busy?'正在保存…':'确认保存草稿'}</Button></div></section></div>}
 </div>;
}
